version: '3'
services:
  aws-es-proxy:
    build: .
    container_name: aws-es-proxy
    env_file:
      - .env
    ports:
      - "9200:9200"
    command: -endpoint ${OPEN_SEARCH_ENDPOINT} -listen 0.0.0.0:9200

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.0.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://aws-es-proxy:9200
    depends_on:
      - aws-es-proxy
    volumes:
      - ./opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
